### ISSUE TITLE
Integration: BentoML for Model Serving

### ISSUE THREAD

**Issue by cosmicBboy** [unionai-oss/unionml#102]
**User Story**: As an ML Engineer I want to serve my UnionML- or Flyte-trained model using BentoML

```python
# bentoml configuration so that 

from unionml import Model

# UnionML deployment journey
# This will create a CRD in Flyte cluster that is a BentoML endpoint users can hit
# - TODO: create an endpoint via backend plugin
model = Model(...)
model.serve(bentoml_service, ..., auto_deploy=YataiConfig(...), approve_before_deploy=True)
model.remote_train(...) # this actually deploys to bentoml 


# This is the Flyte journey:
@task
def produce_model(...) -> nn.Module:
    ...
    return MyModel


# assume that a flyte execution has produced
model = Model()

@model.predictor
def predictor(model_obj: nn.Module, feature: List[float]):
    ...


@workflow
def batch_predict_wf(features: List[float):
    m = produce_model()
    return model.predict_task(m=m, features=features)
    

@workflow
def deploy_model():
    m = produce_model()
    model.deploy_task(m=m)
```

## TODO:

- [ ] create design doc for how the integration will work
- [ ] implement integration

**Comment by cosmicBboy** [comment]
will this need a backend plugin?

**Comment by sugatoray** [comment]
Once you start implementing this, `bentoml` will become a dependency. At that point it will also require `bentoml` on conda-forge channel to properly package `unionml` on conda-forge.

I have already started adding `bentoml` to conda-forge.

- https://github.com/conda-forge/staged-recipes/pull/19457

**Comment by cosmicBboy** [comment]
# Design Doc

The UnionML <> BentoML integration should facilitate the creation of [bentos](https://docs.bentoml.org/en/latest/tutorial.html#building-a-bento)... this is the model-packaging entity that can be served locally, on [yatai](https://docs.bentoml.org/en/latest/concepts/deploy.html#deploy-with-yatai), or on some [target cloud infra](https://docs.bentoml.org/en/latest/concepts/deploy.html#deploy-with-bentoctl) like AWS lambda.

This will require an adaptor class that converts UnionML functions/constructs into BentoML constructs.

This would mean:
- saving UnionML-trained models into the local BentoML model store: https://docs.bentoml.org/en/latest/tutorial.html#saving-models-with-bentoml
- translating `unionml.Model.predict_task` to the [bentoml service API](https://docs.bentoml.org/en/latest/tutorial.html#creating-a-service).
- [building](https://docs.bentoml.org/en/latest/tutorial.html#building-a-bento) the resulting bento
- [containerizing it](https://docs.bentoml.org/en/latest/tutorial.html#generate-docker-image) and convenience functions for running the bento on a docker process.
- creating a `unionml init` template that contains the minimum working code/config for training a model with unionml, serving it locally, with instructions on how to deploy the model to one or just a few of the cloud targets (e.g. AWS Lambda and/or Sagemaker)

**Deployment Documentation:** UnionML shouldn't handle documentation for any of the specific ways in which one can deploy bentoml models. Simply point them to the [Yatai](https://docs.bentoml.org/projects/yatai/en/latest/index.html) and [Bentoctl docs](https://github.com/bentoml/bentoctl) once the UnionML user has trained and successfully served a model locally.

**Comment by cosmicBboy** [comment]
## Handling Data Descriptors

This is an additional spec for how to handle the `svc.api` input/output data descriptors.

UnionML should have reasonable defaults for translating the `Dataset.feature_transformer` and `Model.predictor` function type annotations into the `bentoml.io` data descriptors, but in the case that it can't handle all the cases, unionml should provide a fallback mechanism.

Say we' have a bentoml definition like this:
```python
@svc.api(input=bentoml.io.PandasDataFrame(), output=bentoml.io.JSON())
def predict(dataframe: pd.DataFrame) -> List[float]:
    ...
```

UnionML will try to use the `feature_transformer` input type and `predictor` return type to automatically infer the bentoml.io data descriptors, but can fall back to:

```python
bentoml_service.predict_api(input=..., output=...)
```

## UnionML Runners

A UnionML app should use a [Custom Runner](https://docs.bentoml.org/en/latest/concepts/runner.html#custom-runner) so that the `Model.predict` method is used instead of the built-in bentoml runners so the unionml-defined logic is reused.
