### ISSUE TITLE
[FEATURE] Add `conda` installation option for `unionml`

### ISSUE THREAD

**Issue by sugatoray** [unionai-oss/unionml#128]
It will be helpful to have a conda installation option. Although you could publish the library in your own channel at Anaconda, when other libraries depend on your library and they want to make theirs available on conda-forge channel, `unionml` will be necessary to have on conda-forge channel.

This could possibly facilitate more downstream adoption of `unionml`.

---

:tada: I have started the work of adding `unionml` to conda-forge channel already.

- https://github.com/conda-forge/staged-recipes/pull/19349

Once it is added to conda-forge, you can install it with:

```sh
conda install -c conda-forge unionml
```

:point_right: Or, if you want a rather quicker installation, use `mamba` instead of `conda` for quick environment resolution.

```sh
# install mamba in your conda-environment (if not already installed)
conda install -c conda-forge mamba
# install unionml with mamba instead of conda (for quick installation)
mamba install -c conda-forge unionml
```

**Comment by sugatoray** [comment]
## Notes

Several prerequisites were necessary to take care of before this PR () could be possible.

- Add dependency `mangum` to conda-forge: https://github.com/conda-forge/staged-recipes/pull/19362 

- Update dependency versions on conda-forge for a few `unionml` dependencies:
  - Update `flytekit` from `v0.26.1` to `v1.0.5`: https://github.com/conda-forge/flytekit-feedstock/pull/12
  - Update `flyteidl` from `v0.22.0` to `v1.1.6`: https://github.com/conda-forge/flyteidl-feedstock/pull/12 
  - Update `grpcio-status` from `v1.41.1` to `v1.46.3`: https://github.com/conda-forge/grpcio-status-feedstock/pull/7

---

The PyPI source of `unionml` does not have any `requirements.txt` file at the moment. This causes problems with conda-forge packaging while installing from the source (`.tar.gz` file). I have temporarily circumvented this by dynamically creating the `requirements.txt` file. But this should be fixed at the source here.

- Issue: #126 
- PR (to fix this issue): #125

**Comment by sugatoray** [comment]
cc: @cosmicBboy

**Comment by sugatoray** [comment]
UnionML is now available on conda-forge.

![install_UnionML](https://user-images.githubusercontent.com/10201242/176009369-dc8ae70d-d31a-4239-bd2b-5deac8fc5fae.png)

**Comment by sugatoray** [comment]
cc: @cosmicBboy

**Comment by cosmicBboy** [comment]
fixed by https://github.com/conda-forge/staged-recipes/pull/19349

**Comment by cosmicBboy** [comment]
Re-opening this... just need to add conda-forge install instructions in the README and [installation](https://unionml.readthedocs.io/en/latest/#installation) section of the docs, then we can close this

**Comment by sugatoray** [comment]
I had not checked earler, but there was a similar issue opened already.

- Closes https://github.com/unionai-oss/unionml/issues/73

**Comment by sugatoray** [comment]
@cosmicBboy Could you please assign this PR to me?

**Comment by sugatoray** [comment]
@cosmicBboy Please feel free to close this issue whenever you find it appropriate.

**Comment by eapolinario** [comment]
https://github.com/unionai-oss/unionml/issues/142 tracks the work to add instructions. Closing this ticket.
