### ISSUE TITLE
Add Code of conduct.md and Contributing.md

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [unionai-oss/unionml#174]
I will add  Code of conduct and Contributing to this repo.

**Comment by MrKrishnaAgarwal** [comment]
#take

**Comment by cosmicBboy** [comment]
hi @MrKrishnaAgarwal contributing guide is already in the `docs` section: https://github.com/unionai-oss/unionml/blob/main/docs/source/contributing_guide.md

**Comment by MrKrishnaAgarwal** [comment]
> hi @MrKrishnaAgarwal contributing guide is already in the `docs` section: https://github.com/unionai-oss/unionml/blob/main/docs/source/contributing_guide.md

okay, but I'll add coc

**Comment by cosmicBboy** [comment]
awesome, thanks!
