### ISSUE TITLE
💡 [REQUEST] - Add Gitpod Presence 

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [unionai-oss/unionml#184]
### Start Date

October 2022 (Hacktoberfest) 

### Implementation PR

Will make soon

### Reference Issues

NA

### Summary

Gitpod allows you to view and interact with this code directly in the browser without the need to clone it to your local machine. If you wish to make changes that lead to a pull request, remember to fork the repository then click the Gitpod button in the forked readme. Otherwise, feel free to play around with the code by clicking here.

### Basic Example

I will add Gitpod badge and Gitpod.yml to this Repo, it's super helpful for an open source project and very important too. 

### Drawbacks

NA

### Unresolved questions

NA

**Comment by MrKrishnaAgarwal** [comment]
#self-assign

**Comment by AbhishekTiwari23** [comment]
> this looks great, but I think we should also talk about requirements and consider other options here:
> 
> * github codespaces: https://github.com/features/codespaces
> * jupyterlite: https://jupyterlite.readthedocs.io/en/latest/
> * google colab

Google colab and GitPod are good options. If this is still pending, then I want to contribute

**Comment by MrKrishnaAgarwal** [comment]
I will work on this but I think Gitpod is the best, you can tell and I'll start working.
@cosmicBboy

**Comment by cosmicBboy** [comment]
cool! go ahead with the Gitpod idea @MrKrishnaAgarwal

**Comment by MrKrishnaAgarwal** [comment]
Okay Sure!
I'll make a PR soon....
Thanks

**Comment by MrKrishnaAgarwal** [comment]
@cosmicBboy or @eapolinario 
Kindly review my PR!
