### ISSUE TITLE
Scheduling API: support for offline batch prediction with FlyteRemote to execute on Flyte backend

### ISSUE THREAD

**Issue by cosmicBboy** [unionai-oss/unionml#4]
Currently unionml supports batch predictions through the `model.remote_predict` method, which executes a prediction workflow on the configure flyte backend.

However, the only way of scheduling this today is by pulling out the flyte workflow in `model.prediction_workflow` and using the flyte API to schedule.

The purpose of this task is to come up with some interface for this in unionml.

```python
model.deploy() # deploys workflows to Flyte backend
model.serve() # deploys a model server
model.schedule(...) # schedules a launchplan on Flyte backend
```

**Comment by samhita-alla** [comment]
@cosmicBboy, I see you've written a notion doc on scheduling and serving: https://slime-hunter-536.notion.site/UnionML-Serving-and-Scheduling-RFC-a3aa3ead283e410c98f1bda5fede569c#d33947bb10144eae909269335d49b80e. Should I continue working on this or should this issue be closed?
