### ISSUE TITLE
Fast API app should also expose a healtcheck "/health" endpoint, that should Depends on the loading of PredictParams

### ISSUE THREAD

**Issue by kumare3** [unionai-oss/unionml#41]
This will be required for deploying the fast api app.
Simple example - https://github.com/Kludex/fastapi-health

**Comment by cosmicBboy** [comment]
Just make sure that the model exists in memory and return `True`

**Comment by samhita-alla** [comment]
hey @cosmicBboy! I can work on this issue. I just wanna know what `PredictParams` means here.
