### ISSUE TITLE
fail deployment if branch is dirty, but support --ignore-diff to deploy anyway

### ISSUE THREAD

**Issue by cosmicBboy** [unionai-oss/unionml#56]
Calling `model.remote_deploy()` or using `unionml deploy` on the CLI will deploy all the UnionML Flyte microservices using the current git sha, which will cause issues when a user makes changes to the current branch without committing them.

The purpose of this issue is to raise an Exception if the current git branch is dirty, telling the user to make a commit or use the `--ignore-diff` option if they want to deploy anyway.

**Comment by zevisert** [comment]
#self-assign

**Comment by cosmicBboy** [comment]
fixed by #147
